### ISSUE TITLE
插件的issue

### ISSUE THREAD

**Issue by chrisli30** [OAK-Foundation/extension#3]
地址格式判断错误信息 "Invalid address"
试试把Network做成看起来就不能点的样子
Memo改名叫Note (Optional)，不一定必须要填
List里面，Note要显示在地址的下面
List 现在地址没有group，要按照字母顺序排序,每个group有显示标签
删除的点击加个确认框

**Comment by AmazingBeerBelly** [comment]
Fixed PR #2
